language: php

sudo: false

php:
    - 5.6
    - 7.0

install:
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > ~/.composer/auth.json
    - composer install --prefer-dist

script:
    - php vendor/bin/phpcs --standard=PSR2 View/ Helper/ Test/
    - php vendor/bin/phpmd View/ Helper/ Test/ text cleancode,codesize,controversial,design,naming,unusedcode
    - php vendor/bin/phpcpd View/ Helper/ Test/
    - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

before_script:
- composer self-update
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json

after_script:
    - php vendor/bin/coveralls

env:
    global:
        - secure: "wmMtZU0U92sjj7oE7ml1/GzvR7ndT1QhjGAc3c2EVvILHmGfPWSB4125zYtI6ypLhDXx/Eq9smjOCim420jKaUp3KV4D++VXUI0mNfgO7AJDg+NAaacnh0c+zGRCQ7cc8m7mBZMDSQDnrc9ePWDk8N2fR9f2phzastv7Ds3yMHUtAbMNoL2fW9jr4ZtBpwNsehz+GciA18FQuJ4Lqh9J5WEiChxiS5JcoezC2f9OA+v4JKOo1+uyzMLiYyiGvIL81oTbfgWKfXhLl5DxvOWE8FJKBP80XhKXNYRx4yp75KzcxFm0qdmd3jFRmKuCl2TE7HYcde/7QqR/i21KEPrvd7nuxcr/NFUGQ5RiHQpwZkzih4HDAt4edzkHJMyTtlK/2qLEGdMaVlk/xSk0vUZ9chb/a5qLoDDQvVf0CI2MywVlYdC93GehRez4COYIbiFCfAy0TSav3HriU6n7qTlmQDq1+3hzkMNDQeRf+uucJgTpXu5tWUQnUsLM3TAvPBoGZqUFaA6G1z/E3PjVZ5CcM0fakm6AXZ7W5WmJ+IwnCheDsAHd5RP6xqGegqABfPTJm6/D1YgI8+YXM96cCHHT7Sk666irNG2gs1dZ/3EtO1mOhz0aq2ILM4992TKWY1ntTMuuwuMHd7Vn9N80JRwhZ4vHjEptnCQzhZGsqpC16PQ="
        - secure: "Qoy14H89ZXN/Ui+1Cr34ZXn1vmzHVAsLs81/kQNW/KZ47NlDdeqlBXC3WZ8OH+pPe8CDzNrPuhYK+sf0ZQh3rlplUmTgLmzRfEkcucA1+GrR0uIE5pcvnM8W1a3NtNSqRsrvXcWWuj2rX3wjbe29kObdZnmcbSWDmvlkcm5+jcVVvh8/PnTsWyMv+8xd2vYIJzVcr31hJahlImMWtU876TADHRtVipbZSQIXVxQnf8TKzEPAj6a5s0qlWk52bnqxIFR1BGhAO8HSTPeSg+fa6JqMA+RZouhViwhMPphLaSzDBeVhNlpGxlXAUiXoetOOhrr7IKKEq9YcOFfZesJchw02c7Cv4beYaeFORNmMVzFBCL8j8vnP82oic8rgU9/hWPvaYLLZ+F6Vz44Whj1l2OA+6Pt/TfKH62Y3Nmcbp0EncvQHtrfhL444W2CV78Fn9RTYES8qAS0UO+/yXD1ZZ0o1IKahGSlqb0eQfZRuDHwEZNRWxdTxcRLwtcZBuhobGfnfo6M3DEFprde+z5wsbCPLmjXpxP1zdtOvswzJhqgssljnpL6V+mMEApLGRlc8tNpT4Dvkp0jugRj/fR59wScWuxZJSYEspyOQR/3alHrwtOZDR0aK4bvDpO44ppu0NCAB32wxy1jjRh7hl+is8MF3atiyrpA8QFgFMxNOdoE="
